### ISSUE TITLE
What config can I set?

### ISSUE THREAD

**Issue by pitzcarraldo** [Tjatse/pm2-ant#2]
Hi, thank you for this work.
I've found this project during try to connect pm2 with Graphite and Statsd. But I'm not good in Graphite and Statsd. So I don't know how to use this with my project.
I have clone and ran this my machine, but I don't know how can I set config what related with graphite and statsd. Where can I see the list of config for it?
Understand me. I'm a beginner of PM2 and other things.
Thank you.
Enjoy code.

**Comment by Tjatse** [comment]
It's still in developing and being paused months.

**Comment by pitzcarraldo** [comment]
Thanks for reply.
Good luck ;)
